### ISSUE TITLE
handle problem in eval.py

### ISSUE THREAD

**Issue by Gokulapriyan-B** [akoepke/audio-retrieval-benchmark#1]
When running eval.py in windows, line 101,

cmd = f"python test.py --config {config_path} --resume {trained_model_path} --device 0 --eval_from_training_config >&1 | tee logs_eval\log_{group_id}_{seed}.txt"

is giving output "The handle could not be duplicated during redirection of handle 1." Due to this, no log_{group_id}_{seed}.txt is created in the logs_eval folder.

**Comment by oncescuandreea** [comment]
Hi, we have updated our code to hopefully work on Windows for the eval.py script. Please follow the instructions here https://github.com/akoepke/audio-retrieval-benchmark#for-windows-users-only-follow-these-instructions-windows-info
