### ISSUE TITLE
Training issue for MMT

### ISSUE THREAD

**Issue by Gokulapriyan-B** [akoepke/audio-retrieval-benchmark#2]
When trying to train the MMT model, the error is popping up. What is the solution to this?  

![1](https://user-images.githubusercontent.com/79996558/176207806-6463cc14-db10-4ed6-a94b-bf907ab60e7b.png)

P.S.. While loading dataset, the expert vggish or vggsound is not available. Is this an issue?

**Comment by akoepke** [comment]
Hi,
It looks as if you did not download the features before running the training. For CLOTHO, you can download the features with `python3 misc/sync_experts.py --dataset CLOTHO`.
The feature download is explained in more detail in our [README](https://github.com/akoepke/audio-retrieval-benchmark#requirements-and-datasets).
