### ISSUE TITLE
How to process the raw audio into features?

### ISSUE THREAD

**Issue by Darius-H** [akoepke/audio-retrieval-benchmark#3]
If i have raw audio data. How to transform them into the features like  SoundDescs fatures, Is there any code in the project can do this?
How to transform raw audio data into the form like the image below.
![image](https://user-images.githubusercontent.com/49788663/205351630-071c9868-a518-4028-8986-bb04a2b734c0.png)

**Comment by oncescuandreea** [comment]
Hi!

To obtain the features in the image you have attached, we have used a private repo which we cannot make public. However, there are resources online to help with that. For vggish features we have started from [this code](https://github.com/tensorflow/models/blob/master/research/audioset/vggish/README.md), for vggsound features you can obtain the pre-trained model H from [here](https://github.com/hche11/VGGSound) and follow the appendix in [here](https://arxiv.org/pdf/2105.02192.pdf) on how to extract the features. Similarly for word2vec you could use [this](https://radimrehurek.com/gensim/models/word2vec.html). We hope this helps.

**Comment by bfan1256** [comment]
Hey @Darius-H - did you ever get an implementation, seems a little frustrating that people want to use this benchmark and aren't able to really test it on their own audio....

**Comment by Darius-H** [comment]
> @bfan1256 

I tried their multimodal transformer model, it runs successfully with their data.
